blank_issues_enabled: false
contact_links:
  - name: Plugin reviews
    url: https://plugins.jetbrains.com/plugin/30373-ayu-islands/reviews
    about: Leave a review or read feedback on JetBrains Marketplace
