package dev.ayuislands.settings

import dev.ayuislands.syntax.PrimitiveCategory
import dev.ayuislands.syntax.PrimitiveCategory.ANNOTATION
import dev.ayuislands.syntax.PrimitiveCategory.CLASS_DECL
import dev.ayuislands.syntax.PrimitiveCategory.COMMENT
import dev.ayuislands.syntax.PrimitiveCategory.DOCUMENTATION
import dev.ayuislands.syntax.PrimitiveCategory.FUNCTION_DECL
import dev.ayuislands.syntax.PrimitiveCategory.GENERICS
import dev.ayuislands.syntax.PrimitiveCategory.INSTANCE_FIELD
import dev.ayuislands.syntax.PrimitiveCategory.INTERFACE_DECL
import dev.ayuislands.syntax.PrimitiveCategory.KEYWORD
import dev.ayuislands.syntax.PrimitiveCategory.LOCAL_VAR
import dev.ayuislands.syntax.PrimitiveCategory.NUMBER_LITERAL
import dev.ayuislands.syntax.PrimitiveCategory.OPERATOR
import dev.ayuislands.syntax.PrimitiveCategory.PARAMETER
import dev.ayuislands.syntax.PrimitiveCategory.STATIC_FIELD
import dev.ayuislands.syntax.PrimitiveCategory.STRING_LITERAL
import dev.ayuislands.syntax.PrimitiveCategory.TYPE_REF

internal data class SyntaxPreviewSpec(
    val language: String,
    val fileName: String,
    val standardFileTypeName: String,
    val defaultExtension: String,
    val resourceName: String,
    val demonstratedCategories: Set<PrimitiveCategory>,
)

private data class PreviewFileTypeHint(
    val standardName: String,
    val extension: String,
)

internal object SyntaxPreviewCatalog {
    private val specifications =
        listOf(
            spec(
                "Kotlin",
                "PresetPreview.kt",
                fileType("Kotlin", "kt"),
                "kotlin.txt",
                COMMENT,
                DOCUMENTATION,
                STRING_LITERAL,
                CLASS_DECL,
                ANNOTATION,
                LOCAL_VAR,
                FUNCTION_DECL,
                INSTANCE_FIELD,
                INTERFACE_DECL,
                KEYWORD,
                PARAMETER,
                NUMBER_LITERAL,
                TYPE_REF,
            ),
            spec(
                "Java",
                "PresetPreview.java",
                fileType("JAVA", "java"),
                "java.txt",
                COMMENT,
                DOCUMENTATION,
                CLASS_DECL,
                ANNOTATION,
                OPERATOR,
                FUNCTION_DECL,
                PARAMETER,
                INSTANCE_FIELD,
                INTERFACE_DECL,
                STRING_LITERAL,
                KEYWORD,
                LOCAL_VAR,
                NUMBER_LITERAL,
                STATIC_FIELD,
            ),
            spec(
                "Python",
                "preset_preview.py",
                fileType("Python", "py"),
                "python.txt",
                ANNOTATION,
                OPERATOR,
                DOCUMENTATION,
                STRING_LITERAL,
                FUNCTION_DECL,
                KEYWORD,
                COMMENT,
                NUMBER_LITERAL,
                PARAMETER,
                TYPE_REF,
                LOCAL_VAR,
                GENERICS,
            ),
            spec(
                "JavaScript",
                "preset-preview.js",
                fileType("JavaScript", "js"),
                "javascript.txt",
                COMMENT,
                DOCUMENTATION,
                ANNOTATION,
                LOCAL_VAR,
                INSTANCE_FIELD,
                KEYWORD,
                CLASS_DECL,
                NUMBER_LITERAL,
                PARAMETER,
                STRING_LITERAL,
                TYPE_REF,
                STATIC_FIELD,
                OPERATOR,
                FUNCTION_DECL,
            ),
            spec(
                "TypeScript",
                "preset-preview.ts",
                fileType("TypeScript", "ts"),
                "typescript.txt",
                COMMENT,
                DOCUMENTATION,
                INTERFACE_DECL,
                CLASS_DECL,
                GENERICS,
                TYPE_REF,
                KEYWORD,
                LOCAL_VAR,
                PARAMETER,
                FUNCTION_DECL,
                ANNOTATION,
                INSTANCE_FIELD,
            ),
            spec(
                "Go",
                "preset_preview.go",
                fileType("Go", "go"),
                "go.txt",
                COMMENT,
                NUMBER_LITERAL,
                STRING_LITERAL,
                FUNCTION_DECL,
                TYPE_REF,
                LOCAL_VAR,
                KEYWORD,
                INTERFACE_DECL,
                CLASS_DECL,
                PARAMETER,
                INSTANCE_FIELD,
                ANNOTATION,
                OPERATOR,
            ),
            spec(
                "Rust",
                "preset_preview.rs",
                fileType("Rust", "rs"),
                "rust.txt",
                COMMENT,
                DOCUMENTATION,
                NUMBER_LITERAL,
                STRING_LITERAL,
                FUNCTION_DECL,
                ANNOTATION,
                CLASS_DECL,
                PARAMETER,
                KEYWORD,
                TYPE_REF,
                OPERATOR,
                GENERICS,
                LOCAL_VAR,
                STATIC_FIELD,
            ),
            spec(
                "CSS",
                "preview.css",
                fileType("CSS", "css"),
                "css.txt",
                OPERATOR,
                CLASS_DECL,
                KEYWORD,
                NUMBER_LITERAL,
                STRING_LITERAL,
                ANNOTATION,
                LOCAL_VAR,
            ),
            spec("HTML", "preview.html", fileType("HTML", "html"), "html.txt", ANNOTATION, STRING_LITERAL, KEYWORD),
            spec("JSON", "preview.json", fileType("JSON", "json"), "json.txt", NUMBER_LITERAL, STRING_LITERAL),
            spec("YAML", "preview.yaml", fileType("YAML", "yaml"), "yaml.txt", STRING_LITERAL, ANNOTATION, OPERATOR),
            spec("Markdown", "preview.md", fileType("Markdown", "md"), "markdown.txt", KEYWORD, DOCUMENTATION, COMMENT),
            spec(
                "Swift",
                "Preview.swift",
                fileType("Swift", "swift"),
                "swift.txt",
                CLASS_DECL,
                PARAMETER,
                TYPE_REF,
                ANNOTATION,
                KEYWORD,
                FUNCTION_DECL,
                INSTANCE_FIELD,
                LOCAL_VAR,
                NUMBER_LITERAL,
                INTERFACE_DECL,
                STRING_LITERAL,
                GENERICS,
                COMMENT,
                STATIC_FIELD,
                DOCUMENTATION,
            ),
            spec(
                "Angular",
                "Preview.component.html",
                fileType("HTML", "html"),
                "angular.txt",
                ANNOTATION,
                OPERATOR,
                LOCAL_VAR,
            ),
            spec(
                "Apple plist",
                "Info.plist",
                fileType("XML", "plist"),
                "apple-plist.txt",
                KEYWORD,
                NUMBER_LITERAL,
                OPERATOR,
            ),
            spec(
                "C# (ReSharper)",
                "Preview.cs",
                fileType("C#", "cs"),
                "csharp-resharper.txt",
                COMMENT,
                DOCUMENTATION,
                NUMBER_LITERAL,
                STRING_LITERAL,
                LOCAL_VAR,
                KEYWORD,
                FUNCTION_DECL,
                OPERATOR,
                STATIC_FIELD,
            ),
            spec(
                "CodeQL",
                "preview.ql",
                fileType("CodeQL", "ql"),
                "codeql.txt",
                KEYWORD,
                CLASS_DECL,
                ANNOTATION,
                FUNCTION_DECL,
                NUMBER_LITERAL,
                STRING_LITERAL,
                PARAMETER,
                LOCAL_VAR,
                TYPE_REF,
                OPERATOR,
            ),
            spec(
                "CoffeeScript",
                "preview.coffee",
                fileType("CoffeeScript", "coffee"),
                "coffeescript.txt",
                CLASS_DECL,
                FUNCTION_DECL,
                KEYWORD,
                NUMBER_LITERAL,
                PARAMETER,
                STRING_LITERAL,
            ),
            spec(
                "Dart",
                "preview.dart",
                fileType("Dart", "dart"),
                "dart.txt",
                ANNOTATION,
                CLASS_DECL,
                FUNCTION_DECL,
                KEYWORD,
                INSTANCE_FIELD,
                STATIC_FIELD,
                GENERICS,
                TYPE_REF,
                OPERATOR,
                PARAMETER,
                LOCAL_VAR,
            ),
            spec("Django", "preview.html", fileType("Django Template", "html"), "django.txt", COMMENT, KEYWORD),
            spec("dotenv", ".env", fileType("dotenv", "env"), "dotenv.txt", INSTANCE_FIELD, STRING_LITERAL, OPERATOR),
            spec("Erlang", "preview.erl", fileType("Erlang", "erl"), "erlang.txt", FUNCTION_DECL, KEYWORD),
            spec(
                "FreeMarker",
                "preview.ftl",
                fileType("FreeMarker", "ftl"),
                "freemarker.txt",
                KEYWORD,
                TYPE_REF,
                NUMBER_LITERAL,
                STRING_LITERAL,
            ),
            spec(
                "GraphQL",
                "preview.graphql",
                fileType("GraphQL", "graphql"),
                "graphql.txt",
                ANNOTATION,
                KEYWORD,
                TYPE_REF,
                NUMBER_LITERAL,
                CLASS_DECL,
                OPERATOR,
            ),
            spec(
                "Groovy",
                "Preview.groovy",
                fileType("Groovy", "groovy"),
                "groovy.txt",
                FUNCTION_DECL,
                LOCAL_VAR,
                PARAMETER,
                KEYWORD,
                DOCUMENTATION,
                STRING_LITERAL,
            ),
            spec(
                "HAML",
                "preview.haml",
                fileType("HAML", "haml"),
                "haml.txt",
                CLASS_DECL,
                COMMENT,
                OPERATOR,
                STRING_LITERAL,
            ),
            spec(
                "JSONPath",
                "preview.jsonpath",
                fileType("JSONPath", "jsonpath"),
                "jsonpath.txt",
                KEYWORD,
                LOCAL_VAR,
                NUMBER_LITERAL,
                FUNCTION_DECL,
            ),
            spec(
                "Lua",
                "preview.lua",
                fileType("Lua", "lua"),
                "lua.txt",
                FUNCTION_DECL,
                LOCAL_VAR,
                NUMBER_LITERAL,
                KEYWORD,
                TYPE_REF,
                CLASS_DECL,
                INSTANCE_FIELD,
                PARAMETER,
                DOCUMENTATION,
            ),
            spec(
                "Objective-C",
                "Preview.m",
                fileType("Objective-C", "m"),
                "objective-c.txt",
                KEYWORD,
                FUNCTION_DECL,
                OPERATOR,
                TYPE_REF,
            ),
            spec(
                "PHP",
                "preview.php",
                fileType("PHP", "php"),
                "php.txt",
                COMMENT,
                DOCUMENTATION,
                LOCAL_VAR,
                KEYWORD,
                NUMBER_LITERAL,
                OPERATOR,
                PARAMETER,
                STRING_LITERAL,
                CLASS_DECL,
                INTERFACE_DECL,
                FUNCTION_DECL,
                ANNOTATION,
                INSTANCE_FIELD,
                STATIC_FIELD,
                TYPE_REF,
            ),
            spec(
                "PowerShell",
                "preview.ps1",
                fileType("PowerShell", "ps1"),
                "powershell.txt",
                KEYWORD,
                NUMBER_LITERAL,
                LOCAL_VAR,
                FUNCTION_DECL,
                PARAMETER,
                TYPE_REF,
                OPERATOR,
            ),
            spec(
                "Properties files",
                "preview.properties",
                fileType("Properties", "properties"),
                "properties.txt",
                STRING_LITERAL,
                OPERATOR,
            ),
            spec(
                "Qute",
                "preview.html",
                fileType("Qute", "html"),
                "qute.txt",
                KEYWORD,
                OPERATOR,
                NUMBER_LITERAL,
                LOCAL_VAR,
                STRING_LITERAL,
            ),
            spec(
                "Ruby",
                "preview.rb",
                fileType("Ruby", "rb"),
                "ruby.txt",
                COMMENT,
                LOCAL_VAR,
                STRING_LITERAL,
                KEYWORD,
                FUNCTION_DECL,
                NUMBER_LITERAL,
                OPERATOR,
                TYPE_REF,
                INSTANCE_FIELD,
                INTERFACE_DECL,
            ),
            spec(
                "Sass",
                "preview.scss",
                fileType("SCSS", "scss"),
                "sass.txt",
                COMMENT,
                KEYWORD,
                CLASS_DECL,
                NUMBER_LITERAL,
                STRING_LITERAL,
                LOCAL_VAR,
            ),
            spec(
                "Scala",
                "Preview.scala",
                fileType("Scala", "scala"),
                "scala.txt",
                DOCUMENTATION,
                NUMBER_LITERAL,
                OPERATOR,
                STRING_LITERAL,
                TYPE_REF,
                LOCAL_VAR,
                CLASS_DECL,
                INTERFACE_DECL,
                FUNCTION_DECL,
                KEYWORD,
                PARAMETER,
                ANNOTATION,
            ),
            spec("Slim", "preview.slim", fileType("Slim", "slim"), "slim.txt", CLASS_DECL, COMMENT, STRING_LITERAL),
            spec(
                "Velocity",
                "preview.vm",
                fileType("Velocity", "vm"),
                "velocity.txt",
                KEYWORD,
                TYPE_REF,
                NUMBER_LITERAL,
                STRING_LITERAL,
            ),
            spec("Vue", "Preview.vue", fileType("Vue", "vue"), "vue.txt", OPERATOR),
            spec("XML", "preview.xml", fileType("XML", "xml"), "xml.txt", ANNOTATION, STRING_LITERAL, KEYWORD),
        ).associateBy(SyntaxPreviewSpec::language)

    fun find(language: String): SyntaxPreviewSpec? = specifications[language]

    fun languages(): Set<String> = specifications.keys.toSet()

    fun categories(language: String): Set<PrimitiveCategory> =
        specifications[language]?.demonstratedCategories.orEmpty()

    fun resourceNames(): Set<String> = specifications.values.mapTo(linkedSetOf(), SyntaxPreviewSpec::resourceName)

    private fun spec(
        language: String,
        fileName: String,
        fileTypeHint: PreviewFileTypeHint,
        resourceName: String,
        vararg categories: PrimitiveCategory,
    ): SyntaxPreviewSpec =
        SyntaxPreviewSpec(
            language,
            fileName,
            fileTypeHint.standardName,
            fileTypeHint.extension,
            resourceName,
            categories.toSet(),
        )

    private fun fileType(
        standardName: String,
        extension: String,
    ): PreviewFileTypeHint = PreviewFileTypeHint(standardName, extension)
}
