package dev.ayuislands.syntax

import dev.ayuislands.syntax.PrimitiveCategory.ANNOTATION
import dev.ayuislands.syntax.PrimitiveCategory.CLASS_DECL
import dev.ayuislands.syntax.PrimitiveCategory.COMMENT
import dev.ayuislands.syntax.PrimitiveCategory.DOCUMENTATION
import dev.ayuislands.syntax.PrimitiveCategory.FUNCTION_DECL
import dev.ayuislands.syntax.PrimitiveCategory.GENERICS
import dev.ayuislands.syntax.PrimitiveCategory.INSTANCE_FIELD
import dev.ayuislands.syntax.PrimitiveCategory.INTERFACE_DECL
import dev.ayuislands.syntax.PrimitiveCategory.KEYWORD
import dev.ayuislands.syntax.PrimitiveCategory.LOCAL_VAR
import dev.ayuislands.syntax.PrimitiveCategory.NUMBER_LITERAL
import dev.ayuislands.syntax.PrimitiveCategory.OPERATOR
import dev.ayuislands.syntax.PrimitiveCategory.PARAMETER
import dev.ayuislands.syntax.PrimitiveCategory.STATIC_FIELD
import dev.ayuislands.syntax.PrimitiveCategory.STRING_LITERAL
import dev.ayuislands.syntax.PrimitiveCategory.TYPE_REF

internal data class SyntaxPreviewSpec(
    val language: String,
    val fileName: String,
    val standardFileTypeName: String,
    val defaultExtension: String,
    val resourceName: String,
    val demonstratedCategories: Set<PrimitiveCategory>,
    val semanticOnlyCategories: Set<PrimitiveCategory> = emptySet(),
)

internal data class FileTypeHint(
    val standardName: String,
    val extension: String,
)

internal object SyntaxPreviewCatalog {
    private val specifications =
        listOf(
            syntaxPreviewSpec(
                "Kotlin",
                "PresetPreview.kt",
                previewFileType("Kotlin", "kt"),
                "kotlin.txt",
                COMMENT,
                DOCUMENTATION,
                STRING_LITERAL,
                CLASS_DECL,
                ANNOTATION,
                LOCAL_VAR,
                FUNCTION_DECL,
                INSTANCE_FIELD,
                INTERFACE_DECL,
                KEYWORD,
                PARAMETER,
                NUMBER_LITERAL,
                GENERICS,
                TYPE_REF,
            ),
            syntaxPreviewSpec(
                "Java",
                "PresetPreview.java",
                previewFileType("JAVA", "java"),
                "java.txt",
                COMMENT,
                DOCUMENTATION,
                OPERATOR,
                STRING_LITERAL,
                KEYWORD,
                NUMBER_LITERAL,
            ),
            syntaxPreviewSpec(
                "Python",
                "preset_preview.py",
                previewFileType("Python", "py"),
                "python.txt",
                ANNOTATION,
                OPERATOR,
                DOCUMENTATION,
                STRING_LITERAL,
                FUNCTION_DECL,
                KEYWORD,
                COMMENT,
                NUMBER_LITERAL,
                PARAMETER,
                TYPE_REF,
                LOCAL_VAR,
                GENERICS,
            ).copy(semanticOnlyCategories = setOf(GENERICS)),
            syntaxPreviewSpec(
                "JavaScript",
                "preset-preview.js",
                previewFileType("JavaScript", "js"),
                "javascript.txt",
                ANNOTATION,
                LOCAL_VAR,
                INSTANCE_FIELD,
                KEYWORD,
                CLASS_DECL,
                NUMBER_LITERAL,
                PARAMETER,
                STRING_LITERAL,
                TYPE_REF,
                STATIC_FIELD,
                OPERATOR,
                FUNCTION_DECL,
            ).copy(semanticOnlyCategories = setOf(TYPE_REF)),
            syntaxPreviewSpec(
                "TypeScript",
                "preset-preview.ts",
                previewFileType("TypeScript", "ts"),
                "typescript.txt",
                INTERFACE_DECL,
                CLASS_DECL,
                GENERICS,
                TYPE_REF,
                KEYWORD,
                LOCAL_VAR,
                PARAMETER,
                FUNCTION_DECL,
                ANNOTATION,
                INSTANCE_FIELD,
            ),
            syntaxPreviewSpec(
                "Go",
                "preset_preview.go",
                previewFileType("Go", "go"),
                "go.txt",
                COMMENT,
                NUMBER_LITERAL,
                STRING_LITERAL,
                FUNCTION_DECL,
                TYPE_REF,
                LOCAL_VAR,
                KEYWORD,
                INTERFACE_DECL,
                CLASS_DECL,
                PARAMETER,
                INSTANCE_FIELD,
                OPERATOR,
            ),
            syntaxPreviewSpec(
                "Rust",
                "preset_preview.rs",
                previewFileType("Rust", "rs"),
                "rust.txt",
                COMMENT,
                DOCUMENTATION,
                NUMBER_LITERAL,
                STRING_LITERAL,
                FUNCTION_DECL,
                ANNOTATION,
                CLASS_DECL,
                PARAMETER,
                KEYWORD,
                TYPE_REF,
                OPERATOR,
                GENERICS,
                LOCAL_VAR,
                STATIC_FIELD,
            ),
            syntaxPreviewSpec(
                "CSS",
                "preview.css",
                previewFileType("CSS", "css"),
                "css.txt",
                OPERATOR,
                CLASS_DECL,
                KEYWORD,
                NUMBER_LITERAL,
                STRING_LITERAL,
                ANNOTATION,
                LOCAL_VAR,
            ),
            syntaxPreviewSpec(
                "HTML",
                "preview.html",
                previewFileType("HTML", "html"),
                "html.txt",
                ANNOTATION,
                STRING_LITERAL,
                KEYWORD,
            ),
            syntaxPreviewSpec(
                "JSON",
                "preview.json",
                previewFileType("JSON", "json"),
                "json.txt",
                NUMBER_LITERAL,
                STRING_LITERAL,
            ),
            syntaxPreviewSpec(
                "YAML",
                "preview.yaml",
                previewFileType("YAML", "yaml"),
                "yaml.txt",
                STRING_LITERAL,
                ANNOTATION,
                OPERATOR,
            ),
            syntaxPreviewSpec(
                "Markdown",
                "preview.md",
                previewFileType("Markdown", "md"),
                "markdown.txt",
                KEYWORD,
                DOCUMENTATION,
                COMMENT,
            ),
            syntaxPreviewSpec(
                "Swift",
                "Preview.swift",
                previewFileType("Swift", "swift"),
                "swift.txt",
                CLASS_DECL,
                PARAMETER,
                ANNOTATION,
                KEYWORD,
                FUNCTION_DECL,
                INSTANCE_FIELD,
                LOCAL_VAR,
                NUMBER_LITERAL,
                INTERFACE_DECL,
                STRING_LITERAL,
                COMMENT,
                OPERATOR,
            ),
            syntaxPreviewSpec(
                "Angular",
                "Preview.component.html",
                previewFileType("HTML", "html"),
                "angular.txt",
                ANNOTATION,
                OPERATOR,
                LOCAL_VAR,
            ),
            syntaxPreviewSpec(
                "Apple plist",
                "Info.plist",
                previewFileType("XML", "plist"),
                "apple-plist.txt",
                KEYWORD,
                NUMBER_LITERAL,
                OPERATOR,
            ),
            syntaxPreviewSpec(
                "C# (ReSharper)",
                "Preview.cs",
                previewFileType("C#", "cs"),
                "csharp-resharper.txt",
                COMMENT,
                DOCUMENTATION,
                NUMBER_LITERAL,
                STRING_LITERAL,
                LOCAL_VAR,
                KEYWORD,
                FUNCTION_DECL,
                OPERATOR,
                STATIC_FIELD,
            ),
            syntaxPreviewSpec(
                "CodeQL",
                "preview.ql",
                previewFileType("CodeQL", "ql"),
                "codeql.txt",
                KEYWORD,
                CLASS_DECL,
                ANNOTATION,
                FUNCTION_DECL,
                NUMBER_LITERAL,
                STRING_LITERAL,
                PARAMETER,
                LOCAL_VAR,
                TYPE_REF,
                OPERATOR,
            ),
            syntaxPreviewSpec(
                "CoffeeScript",
                "preview.coffee",
                previewFileType("CoffeeScript", "coffee"),
                "coffeescript.txt",
                FUNCTION_DECL,
                KEYWORD,
                NUMBER_LITERAL,
                PARAMETER,
                STRING_LITERAL,
            ).copy(semanticOnlyCategories = setOf(PARAMETER)),
            syntaxPreviewSpec(
                "Dart",
                "preview.dart",
                previewFileType("Dart", "dart"),
                "dart.txt",
                ANNOTATION,
                CLASS_DECL,
                FUNCTION_DECL,
                KEYWORD,
                INSTANCE_FIELD,
                STATIC_FIELD,
                GENERICS,
                TYPE_REF,
                OPERATOR,
                PARAMETER,
                LOCAL_VAR,
                STRING_LITERAL,
            ),
            syntaxPreviewSpec(
                "Django",
                "preview.html",
                previewFileType("Django Template", "html"),
                "django.txt",
                COMMENT,
                KEYWORD,
            ),
            syntaxPreviewSpec(
                "dotenv",
                ".env",
                previewFileType("dotenv", "env"),
                "dotenv.txt",
                INSTANCE_FIELD,
                STRING_LITERAL,
                OPERATOR,
            ),
            syntaxPreviewSpec(
                "Erlang",
                "preview.erl",
                previewFileType("Erlang", "erl"),
                "erlang.txt",
                FUNCTION_DECL,
                KEYWORD,
            ),
            syntaxPreviewSpec(
                "FreeMarker",
                "preview.ftl",
                previewFileType("FreeMarker", "ftl"),
                "freemarker.txt",
                KEYWORD,
                TYPE_REF,
                NUMBER_LITERAL,
                STRING_LITERAL,
            ),
            syntaxPreviewSpec(
                "GraphQL",
                "preview.graphql",
                previewFileType("GraphQL", "graphql"),
                "graphql.txt",
                ANNOTATION,
                KEYWORD,
                TYPE_REF,
                NUMBER_LITERAL,
                CLASS_DECL,
                OPERATOR,
            ),
            syntaxPreviewSpec(
                "Groovy",
                "Preview.groovy",
                previewFileType("Groovy", "groovy"),
                "groovy.txt",
                FUNCTION_DECL,
                LOCAL_VAR,
                PARAMETER,
                KEYWORD,
                DOCUMENTATION,
                STRING_LITERAL,
            ).copy(semanticOnlyCategories = setOf(DOCUMENTATION)),
            syntaxPreviewSpec(
                "HAML",
                "preview.haml",
                previewFileType("HAML", "haml"),
                "haml.txt",
                CLASS_DECL,
                COMMENT,
                OPERATOR,
                STRING_LITERAL,
            ),
            syntaxPreviewSpec(
                "JSONPath",
                "preview.jsonpath",
                previewFileType("JSONPath", "jsonpath"),
                "jsonpath.txt",
                KEYWORD,
                LOCAL_VAR,
                NUMBER_LITERAL,
                FUNCTION_DECL,
            ),
            syntaxPreviewSpec(
                "Lua",
                "preview.lua",
                previewFileType("Lua", "lua"),
                "lua.txt",
                FUNCTION_DECL,
                LOCAL_VAR,
                NUMBER_LITERAL,
                KEYWORD,
                TYPE_REF,
                CLASS_DECL,
                INSTANCE_FIELD,
                PARAMETER,
                DOCUMENTATION,
            ),
            syntaxPreviewSpec(
                "Objective-C",
                "Preview.m",
                previewFileType("Objective-C", "m"),
                "objective-c.txt",
                KEYWORD,
                FUNCTION_DECL,
                OPERATOR,
                TYPE_REF,
            ),
            syntaxPreviewSpec(
                "PHP",
                "preview.php",
                previewFileType("PHP", "php"),
                "php.txt",
                COMMENT,
                DOCUMENTATION,
                LOCAL_VAR,
                KEYWORD,
                NUMBER_LITERAL,
                OPERATOR,
                PARAMETER,
                STRING_LITERAL,
                CLASS_DECL,
                INTERFACE_DECL,
                FUNCTION_DECL,
                ANNOTATION,
                INSTANCE_FIELD,
                STATIC_FIELD,
                TYPE_REF,
            ).copy(
                semanticOnlyCategories =
                    setOf(
                        PARAMETER,
                        CLASS_DECL,
                        INTERFACE_DECL,
                        FUNCTION_DECL,
                        ANNOTATION,
                        INSTANCE_FIELD,
                        STATIC_FIELD,
                        TYPE_REF,
                    ),
            ),
            syntaxPreviewSpec(
                "PowerShell",
                "preview.ps1",
                previewFileType("PowerShell", "ps1"),
                "powershell.txt",
                KEYWORD,
                NUMBER_LITERAL,
                LOCAL_VAR,
                FUNCTION_DECL,
                PARAMETER,
                TYPE_REF,
                OPERATOR,
            ),
            syntaxPreviewSpec(
                "Properties files",
                "preview.properties",
                previewFileType("Properties", "properties"),
                "properties.txt",
                STRING_LITERAL,
                OPERATOR,
            ),
            syntaxPreviewSpec(
                "Qute",
                "preview.qute.html",
                previewFileType("Qute", "html"),
                "qute.txt",
                KEYWORD,
                OPERATOR,
                NUMBER_LITERAL,
                LOCAL_VAR,
                STRING_LITERAL,
            ),
            syntaxPreviewSpec(
                "Ruby",
                "preview.rb",
                previewFileType("Ruby", "rb"),
                "ruby.txt",
                COMMENT,
                LOCAL_VAR,
                STRING_LITERAL,
                KEYWORD,
                FUNCTION_DECL,
                NUMBER_LITERAL,
                OPERATOR,
                TYPE_REF,
                INSTANCE_FIELD,
            ),
            syntaxPreviewSpec(
                "Sass",
                "preview.scss",
                previewFileType("SCSS", "scss"),
                "sass.txt",
                COMMENT,
                KEYWORD,
                CLASS_DECL,
                NUMBER_LITERAL,
                STRING_LITERAL,
                LOCAL_VAR,
            ),
            syntaxPreviewSpec(
                "Scala",
                "Preview.scala",
                previewFileType("Scala", "scala"),
                "scala.txt",
                DOCUMENTATION,
                COMMENT,
                NUMBER_LITERAL,
                OPERATOR,
                STRING_LITERAL,
                TYPE_REF,
                LOCAL_VAR,
                CLASS_DECL,
                INTERFACE_DECL,
                FUNCTION_DECL,
                KEYWORD,
                PARAMETER,
                ANNOTATION,
            ),
            syntaxPreviewSpec(
                "Slim",
                "preview.slim",
                previewFileType("Slim", "slim"),
                "slim.txt",
                CLASS_DECL,
                COMMENT,
                STRING_LITERAL,
            ),
            syntaxPreviewSpec(
                "Velocity",
                "preview.vm",
                previewFileType("Velocity", "vm"),
                "velocity.txt",
                KEYWORD,
                TYPE_REF,
                NUMBER_LITERAL,
                STRING_LITERAL,
            ),
            syntaxPreviewSpec("Vue", "Preview.vue", previewFileType("Vue", "vue"), "vue.txt", OPERATOR),
            syntaxPreviewSpec(
                "XML",
                "preview.xml",
                previewFileType("XML", "xml"),
                "xml.txt",
                ANNOTATION,
                STRING_LITERAL,
                KEYWORD,
            ),
        ).plus(SpecializedPreviewSpecs.entries).associateBy(SyntaxPreviewSpec::language)

    fun find(language: String): SyntaxPreviewSpec? = specifications[language]

    fun languages(): Set<String> = specifications.keys.toSet()

    fun categories(language: String): Set<PrimitiveCategory> =
        specifications[language]?.demonstratedCategories.orEmpty()

    fun entries(): Collection<SyntaxPreviewSpec> = specifications.values
}

internal fun syntaxPreviewSpec(
    language: String,
    fileName: String,
    fileTypeHint: FileTypeHint,
    resourceName: String,
    vararg categories: PrimitiveCategory,
): SyntaxPreviewSpec =
    SyntaxPreviewSpec(
        language,
        fileName,
        fileTypeHint.standardName,
        fileTypeHint.extension,
        resourceName,
        categories.toSet(),
    )

internal fun previewFileType(
    standardName: String,
    extension: String,
): FileTypeHint = FileTypeHint(standardName, extension)
